version: "3.8"

x-default: &default
  networks:
    - demo-net
  # cpus: 0.5
  # mem_limit: 500M
  restart: always
  # init: true
  # privileged: true
  # stdin_open: true
  # tty: true
  logging:
    driver: "json-file"
    options:
      max-size: "10M"
      max-file: "3"

networks:
    demo-net:

volumes: 
    redis_data:
services: 
    redis:
        <<: *default
        image: bitnami/redis:5.0
        container_name: redis_test
        environment:
          - ALLOW_EMPTY_PASSWORD=yes
        # - REDIS_PASSWORD=5Zu7fA8r5eaO
        ports:
          - "127.0.0.1:6389:6379"
        volumes:
          - redis_data/:/data/
        hostname: redis_test
    demo-celery:
        <<: *default
        image: demo-celery/app:1.0
        container_name: demo-app-celery
        build:
            context: ./app
            dockerfile: dockerfile
    monitor-celery:
        <<: *default
        image: demo-celery/monitor:1.0
        container_name: demo-monitor-celery
        build:
            context: ./celery-queue
            dockerfile: dockerfile
        ports:
            - "5556:5555"
        entrypoint: flower
        command: -A tasks --port=5556 --broker=redis://redis:6379/0
        depends_on:
            - redis