version: '2'
services:
  web:
    build:
      context: ./flask_app
      dockerfile: Dockerfile
    restart: always
    ports:
     - "5000:5000"
    depends_on:
      - redis
  worker:
    build:
      context: ./flask_celery
      dockerfile: Dockerfile
    depends_on:
      - redis
  monitor:
    build:
      context: ./flask_celery
      dockerfile: Dockerfile
    ports:
     - "5556:5555"
    entrypoint: flower
    command:  -A tasks --port=5555 --broker=redis://redis:6379/0
    depends_on:
      - redis
  redis:
    image: redis
    container_name: redis_test
