version: "3.3"

services: 
    web:
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints:
                    - node.role == manager
    worker:
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints:
                    - node.labels.celery_worker == true